name: JS file Workflow

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: windows-latest
    steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with: 
        node-version: 16.x
    - run: npm ci
    - uses: sibiraj-s/action-eslint@v2
      with:
        eslint-args: '--ignore-path=.gitignore --quiet'
        extensions: 'js,jsx,ts,tsx'
        annotations: true
    - run: npm test
    - uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ 58bf432f-4870-4123-b95e-ce8502f3314f }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}